# What is the First Day of the Week?

Whether the Gregorian calendar shows Sunday or Monday as the first day of the week depends on where you live.

Do more countries start the week on Sunday or Monday? What about people? What about by continent?

The file `first-day-of-week.csv` shows the first day of the week for each territory. The file `population.csv` shows the population in the year 2020 for each territory in millions, and the file `four-regions.csv` specifies whether each territory is in asia, europe, africa, or the americas.

In [1]:
# FOR GOOGLE COLAB ONLY.
# Uncomment and run the code below. A dialog will appear to upload files.
# Upload 'first-day-of-week.csv', 'population.csv', and 'four-regions.csv'.

# from google.colab import files
# uploaded = files.upload()

In [2]:
import pandas as pd
df = pd.read_csv('first-day-of-week.csv')
df.head()

        territory alpha3 first_day   units paper
0     Afghanistan    AFG       sat  metric    A4
1   Aland Islands    ALA       mon  metric    A4
2         Albania    ALB       mon  metric    A4
3         Algeria    DZA       sat  metric    A4
4  American Samoa    ASM       sun  metric    A4

In [21]:
pop = pd.read_csv('population.csv')

    alpha3  population
187    USA      339.44

In [4]:
regions = pd.read_csv('four-regions.csv')
regions.head()

  alpha3 four_regions
0    AUS         asia
1    BRN         asia
2    KHM         asia
3    CHN         asia
4    FJI         asia

### Project Ideas

- How many territories show Friday, Saturday, Sunday, and Monday as the `first_day` of the week?

- How many people start the week on Friday, Saturday, Sunday, and Monday?
	- Hint: This will involve a `merge`.

- Which of the `four_regions` predominantly start the week on Sunday? On Monday? Are there any regions that are more divided between Sunday and Monday?
	- Hint: This will also involve a `merge`.

In [9]:
df['first_day'].value_counts().reset_index()

  first_day  count
0       mon    186
1       sun     55
2       sat     15
3       fri      1

In [22]:
df_populations = pd.merge(df,pop,on='alpha3', how='left')

df_populations.groupby('first_day')['population'].sum().sort_values(ascending=False).reset_index()

  first_day  population
0       sun     3844.08
1       mon     3600.19
2       sat      431.79
3       fri        0.50

In [75]:
df_regions_populations = pd.merge(df_populations,regions,on='alpha3',how='left')
gr=df_regions_populations.groupby(['four_regions',"first_day"])['population'].sum().reset_index()
gr

   four_regions first_day  population
0        africa       mon      890.44
1        africa       sat      208.31
2        africa       sun      280.38
3      americas       mon      126.93
4      americas       sun      892.42
5          asia       fri        0.50
6          asia       mon     1742.02
7          asia       sat      223.48
8          asia       sun     2660.39
9        europe       mon      840.80
10       europe       sun       10.89

In [91]:
grouped = df_regions_populations.groupby(['four_regions','first_day'])['population'].sum().reset_index()
grouped.loc[grouped.groupby('four_regions')['population'].idxmax()].sort_values(by='population', ascending=False).reset_index(drop=True)

  four_regions first_day  population
0         asia       sun     2660.39
1     americas       sun      892.42
2       africa       mon      890.44
3       europe       mon      840.80